package com.proyecto.quental.chat.model;

import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.trash.TrashHandler;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.TrashedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.trash.model.TrashEntry;

import java.io.Serializable;

/**
 * The base model interface for the Asignacion service. Represents a row in the &quot;Asignacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.proyecto.quental.chat.model.impl.AsignacionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.proyecto.quental.chat.model.impl.AsignacionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Asignacion
 * @see com.proyecto.quental.chat.model.impl.AsignacionImpl
 * @see com.proyecto.quental.chat.model.impl.AsignacionModelImpl
 * @generated
 */
public interface AsignacionModel extends BaseModel<Asignacion>, TrashedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a asignacion model instance should use the {@link Asignacion} interface instead.
     */

    /**
     * Returns the primary key of this asignacion.
     *
     * @return the primary key of this asignacion
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this asignacion.
     *
     * @param primaryKey the primary key of this asignacion
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the asignacion ID of this asignacion.
     *
     * @return the asignacion ID of this asignacion
     */
    public long getAsignacionId();

    /**
     * Sets the asignacion ID of this asignacion.
     *
     * @param asignacionId the asignacion ID of this asignacion
     */
    public void setAsignacionId(long asignacionId);

    /**
     * Returns the user ID of this asignacion.
     *
     * @return the user ID of this asignacion
     */
    public long getUserId();

    /**
     * Sets the user ID of this asignacion.
     *
     * @param userId the user ID of this asignacion
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this asignacion.
     *
     * @return the user uuid of this asignacion
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this asignacion.
     *
     * @param userUuid the user uuid of this asignacion
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the conversacion ID of this asignacion.
     *
     * @return the conversacion ID of this asignacion
     */
    public long getConversacionId();

    /**
     * Sets the conversacion ID of this asignacion.
     *
     * @param conversacionId the conversacion ID of this asignacion
     */
    public void setConversacionId(long conversacionId);

    /**
     * Returns the status of this asignacion.
     *
     * @return the status of this asignacion
     */
    @Override
    public int getStatus();

    /**
     * Returns the trash entry created when this asignacion was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this asignacion.
     *
     * @return the trash entry created when this asignacion was moved to the Recycle Bin
     * @throws SystemException if a system exception occurred
     */
    @Override
    public TrashEntry getTrashEntry() throws PortalException, SystemException;

    /**
     * Returns the class primary key of the trash entry for this asignacion.
     *
     * @return the class primary key of the trash entry for this asignacion
     */
    @Override
    public long getTrashEntryClassPK();

    /**
     * Returns the trash handler for this asignacion.
     *
     * @return the trash handler for this asignacion
     */
    @Override
    public TrashHandler getTrashHandler();

    /**
     * Returns <code>true</code> if this asignacion is in the Recycle Bin.
     *
     * @return <code>true</code> if this asignacion is in the Recycle Bin; <code>false</code> otherwise
     */
    @Override
    public boolean isInTrash();

    /**
     * Returns <code>true</code> if the parent of this asignacion is in the Recycle Bin.
     *
     * @return <code>true</code> if the parent of this asignacion is in the Recycle Bin; <code>false</code> otherwise
     * @throws SystemException if a system exception occurred
     */
    @Override
    public boolean isInTrashContainer();

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.proyecto.quental.chat.model.Asignacion asignacion);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.proyecto.quental.chat.model.Asignacion> toCacheModel();

    @Override
    public com.proyecto.quental.chat.model.Asignacion toEscapedModel();

    @Override
    public com.proyecto.quental.chat.model.Asignacion toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
