package com.proyecto.quental.chat.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.proyecto.quental.chat.model.Asignacion;
import com.proyecto.quental.chat.service.AsignacionLocalServiceUtil;

/**
 * The extended model base implementation for the Asignacion service. Represents a row in the &quot;Asignacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AsignacionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AsignacionImpl
 * @see com.proyecto.quental.chat.model.Asignacion
 * @generated
 */
public abstract class AsignacionBaseImpl extends AsignacionModelImpl
    implements Asignacion {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a asignacion model instance should use the {@link Asignacion} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AsignacionLocalServiceUtil.addAsignacion(this);
        } else {
            AsignacionLocalServiceUtil.updateAsignacion(this);
        }
    }
}
