package com.proyecto.quental.chat.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.proyecto.quental.chat.model.Mensaje;
import com.proyecto.quental.chat.service.MensajeLocalServiceUtil;

/**
 * The extended model base implementation for the Mensaje service. Represents a row in the &quot;Mensaje&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MensajeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MensajeImpl
 * @see com.proyecto.quental.chat.model.Mensaje
 * @generated
 */
public abstract class MensajeBaseImpl extends MensajeModelImpl
    implements Mensaje {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a mensaje model instance should use the {@link Mensaje} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            MensajeLocalServiceUtil.addMensaje(this);
        } else {
            MensajeLocalServiceUtil.updateMensaje(this);
        }
    }
}
