package com.proyecto.quental.chat.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.trash.TrashHandler;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.TrashedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.trash.model.TrashEntry;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Conversacion service. Represents a row in the &quot;Conversacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.proyecto.quental.chat.model.impl.ConversacionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.proyecto.quental.chat.model.impl.ConversacionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Conversacion
 * @see com.proyecto.quental.chat.model.impl.ConversacionImpl
 * @see com.proyecto.quental.chat.model.impl.ConversacionModelImpl
 * @generated
 */
public interface ConversacionModel extends BaseModel<Conversacion>, TrashedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a conversacion model instance should use the {@link Conversacion} interface instead.
     */

    /**
     * Returns the primary key of this conversacion.
     *
     * @return the primary key of this conversacion
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this conversacion.
     *
     * @param primaryKey the primary key of this conversacion
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the conversacion ID of this conversacion.
     *
     * @return the conversacion ID of this conversacion
     */
    public long getConversacionId();

    /**
     * Sets the conversacion ID of this conversacion.
     *
     * @param conversacionId the conversacion ID of this conversacion
     */
    public void setConversacionId(long conversacionId);

    /**
     * Returns the nick name of this conversacion.
     *
     * @return the nick name of this conversacion
     */
    @AutoEscape
    public String getNickName();

    /**
     * Sets the nick name of this conversacion.
     *
     * @param nickName the nick name of this conversacion
     */
    public void setNickName(String nickName);

    /**
     * Returns the create date of this conversacion.
     *
     * @return the create date of this conversacion
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this conversacion.
     *
     * @param createDate the create date of this conversacion
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the fin date of this conversacion.
     *
     * @return the fin date of this conversacion
     */
    public Date getFinDate();

    /**
     * Sets the fin date of this conversacion.
     *
     * @param finDate the fin date of this conversacion
     */
    public void setFinDate(Date finDate);

    /**
     * Returns the categoria of this conversacion.
     *
     * @return the categoria of this conversacion
     */
    @AutoEscape
    public String getCategoria();

    /**
     * Sets the categoria of this conversacion.
     *
     * @param categoria the categoria of this conversacion
     */
    public void setCategoria(String categoria);

    /**
     * Returns the descripcion of this conversacion.
     *
     * @return the descripcion of this conversacion
     */
    @AutoEscape
    public String getDescripcion();

    /**
     * Sets the descripcion of this conversacion.
     *
     * @param descripcion the descripcion of this conversacion
     */
    public void setDescripcion(String descripcion);

    /**
     * Returns the etiquetas of this conversacion.
     *
     * @return the etiquetas of this conversacion
     */
    @AutoEscape
    public String getEtiquetas();

    /**
     * Sets the etiquetas of this conversacion.
     *
     * @param etiquetas the etiquetas of this conversacion
     */
    public void setEtiquetas(String etiquetas);

    /**
     * Returns the asignado of this conversacion.
     *
     * @return the asignado of this conversacion
     */
    public boolean getAsignado();

    /**
     * Returns <code>true</code> if this conversacion is asignado.
     *
     * @return <code>true</code> if this conversacion is asignado; <code>false</code> otherwise
     */
    public boolean isAsignado();

    /**
     * Sets whether this conversacion is asignado.
     *
     * @param asignado the asignado of this conversacion
     */
    public void setAsignado(boolean asignado);

    /**
     * Returns the cerrada of this conversacion.
     *
     * @return the cerrada of this conversacion
     */
    public boolean getCerrada();

    /**
     * Returns <code>true</code> if this conversacion is cerrada.
     *
     * @return <code>true</code> if this conversacion is cerrada; <code>false</code> otherwise
     */
    public boolean isCerrada();

    /**
     * Sets whether this conversacion is cerrada.
     *
     * @param cerrada the cerrada of this conversacion
     */
    public void setCerrada(boolean cerrada);

    /**
     * Returns the status of this conversacion.
     *
     * @return the status of this conversacion
     */
    @Override
    public int getStatus();

    /**
     * Returns the trash entry created when this conversacion was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this conversacion.
     *
     * @return the trash entry created when this conversacion was moved to the Recycle Bin
     * @throws SystemException if a system exception occurred
     */
    @Override
    public TrashEntry getTrashEntry() throws PortalException, SystemException;

    /**
     * Returns the class primary key of the trash entry for this conversacion.
     *
     * @return the class primary key of the trash entry for this conversacion
     */
    @Override
    public long getTrashEntryClassPK();

    /**
     * Returns the trash handler for this conversacion.
     *
     * @return the trash handler for this conversacion
     */
    @Override
    public TrashHandler getTrashHandler();

    /**
     * Returns <code>true</code> if this conversacion is in the Recycle Bin.
     *
     * @return <code>true</code> if this conversacion is in the Recycle Bin; <code>false</code> otherwise
     */
    @Override
    public boolean isInTrash();

    /**
     * Returns <code>true</code> if the parent of this conversacion is in the Recycle Bin.
     *
     * @return <code>true</code> if the parent of this conversacion is in the Recycle Bin; <code>false</code> otherwise
     * @throws SystemException if a system exception occurred
     */
    @Override
    public boolean isInTrashContainer();

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.proyecto.quental.chat.model.Conversacion conversacion);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.proyecto.quental.chat.model.Conversacion> toCacheModel();

    @Override
    public com.proyecto.quental.chat.model.Conversacion toEscapedModel();

    @Override
    public com.proyecto.quental.chat.model.Conversacion toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
