package com.proyecto.quental.chat.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.trash.TrashHandler;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.TrashedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.trash.model.TrashEntry;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Mensaje service. Represents a row in the &quot;Mensaje&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.proyecto.quental.chat.model.impl.MensajeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.proyecto.quental.chat.model.impl.MensajeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Mensaje
 * @see com.proyecto.quental.chat.model.impl.MensajeImpl
 * @see com.proyecto.quental.chat.model.impl.MensajeModelImpl
 * @generated
 */
public interface MensajeModel extends BaseModel<Mensaje>, TrashedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a mensaje model instance should use the {@link Mensaje} interface instead.
     */

    /**
     * Returns the primary key of this mensaje.
     *
     * @return the primary key of this mensaje
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this mensaje.
     *
     * @param primaryKey the primary key of this mensaje
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the mensaje ID of this mensaje.
     *
     * @return the mensaje ID of this mensaje
     */
    public long getMensajeId();

    /**
     * Sets the mensaje ID of this mensaje.
     *
     * @param mensajeId the mensaje ID of this mensaje
     */
    public void setMensajeId(long mensajeId);

    /**
     * Returns the autor of this mensaje.
     *
     * @return the autor of this mensaje
     */
    @AutoEscape
    public String getAutor();

    /**
     * Sets the autor of this mensaje.
     *
     * @param autor the autor of this mensaje
     */
    public void setAutor(String autor);

    /**
     * Returns the create date of this mensaje.
     *
     * @return the create date of this mensaje
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this mensaje.
     *
     * @param createDate the create date of this mensaje
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the contenido of this mensaje.
     *
     * @return the contenido of this mensaje
     */
    @AutoEscape
    public String getContenido();

    /**
     * Sets the contenido of this mensaje.
     *
     * @param contenido the contenido of this mensaje
     */
    public void setContenido(String contenido);

    /**
     * Returns the conversacion ID of this mensaje.
     *
     * @return the conversacion ID of this mensaje
     */
    public long getConversacionId();

    /**
     * Sets the conversacion ID of this mensaje.
     *
     * @param conversacionId the conversacion ID of this mensaje
     */
    public void setConversacionId(long conversacionId);

    /**
     * Returns the status of this mensaje.
     *
     * @return the status of this mensaje
     */
    @Override
    public int getStatus();

    /**
     * Returns the trash entry created when this mensaje was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this mensaje.
     *
     * @return the trash entry created when this mensaje was moved to the Recycle Bin
     * @throws SystemException if a system exception occurred
     */
    @Override
    public TrashEntry getTrashEntry() throws PortalException, SystemException;

    /**
     * Returns the class primary key of the trash entry for this mensaje.
     *
     * @return the class primary key of the trash entry for this mensaje
     */
    @Override
    public long getTrashEntryClassPK();

    /**
     * Returns the trash handler for this mensaje.
     *
     * @return the trash handler for this mensaje
     */
    @Override
    public TrashHandler getTrashHandler();

    /**
     * Returns <code>true</code> if this mensaje is in the Recycle Bin.
     *
     * @return <code>true</code> if this mensaje is in the Recycle Bin; <code>false</code> otherwise
     */
    @Override
    public boolean isInTrash();

    /**
     * Returns <code>true</code> if the parent of this mensaje is in the Recycle Bin.
     *
     * @return <code>true</code> if the parent of this mensaje is in the Recycle Bin; <code>false</code> otherwise
     * @throws SystemException if a system exception occurred
     */
    @Override
    public boolean isInTrashContainer();

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.proyecto.quental.chat.model.Mensaje mensaje);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.proyecto.quental.chat.model.Mensaje> toCacheModel();

    @Override
    public com.proyecto.quental.chat.model.Mensaje toEscapedModel();

    @Override
    public com.proyecto.quental.chat.model.Mensaje toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
